# Run this in the workspace where you want to set up Minecraft modpack server files.

services:
  setup:
    image: eclarift/minecraft-setup:latest
    container_name: minecraft-setup
    volumes:
      - .:/workspace
    profiles:
      - setup
    restart: 'no'
