# https://github.com/Querz/mcaselector

FROM eclipse-temurin:25-jre-alpine

RUN apk add --no-cache bash curl jq

WORKDIR /mcaselector

# MCSelector
RUN echo "========== MCSelector Setup ==========" && \
    echo "[MCSelector] Fetching latest release URL" && \
    latest_url=$( \
        curl -fsSL "https://api.github.com/repos/Querz/mcaselector/releases/latest" | \
        jq -r '.assets[] | select(.name | endswith(".jar")) | .browser_download_url' \
    ) && \
    echo "[MCSelector] Downloading from $latest_url" && \
    curl -fsSL -o mcaselector.jar "$latest_url" && \
    echo "[MCSelector] Preparing executable" && \
    chmod +x mcaselector.jar

# Custom helper scripts
COPY delete-chunks.sh .

ENTRYPOINT ["java", "-jar", "mcaselector.jar"]
